In [1]:
# exception /error handaling

In [2]:
f = open('all.text')

FileNotFoundError: [Errno 2] No such file or directory: 'all.text'

In [3]:
# try and except

In [4]:
try:
    f= open('all.text')
except:
    print("filr dose not exist")

filr dose not exist

In [5]:
try:
    f= open('a1.txt')
    print(var1)
except:
    print("filr dose not exist")

filr dose not exist

In [6]:
# we need to be specific about what kind of error we want to catch

In [7]:
try:
    f= open('a1.txt')
    print(var1)
except FileNotFoundError:
    print("filr dose not exist")

NameError: name 'var1' is not defined

In [10]:
try:
    f= open('a1.txt')
    print(var1)
except FileNotFoundError:
    print("filr dose not exist")
except Exception:
    print("something went wrong")

something went wrong

In [11]:
try:
    f= open('a1.txt')
    print(var1)
except FileNotFoundError:
    print("filr dose not exist")
except Exception as e:
    print(e)

name 'var1' is not defined

In [12]:
# else -> if try block raise any exception this will run

In [14]:
try:
    f= open('a1.txt')
except FileNotFoundError:
    print("filr dose not exist")
except Exception as e:
    print(e)
else:
    print(f.read())
    f.close()

This is the first line

In [15]:
# finally

In [18]:
try:
    f= open('a1.txt')
    print(var1) 
except FileNotFoundError:
    print("filr dose not exist")
except Exception as e:
    print(e)
else:
    print(f.read())
    f.close()
finally:
    print("run complete")

name 'var1' is not defined
run complete

In [19]:
try:
    f= open('a1.txt')
    if f.name =='a1.txt':
        raise Exception
except FileNotFoundError:
    print("filr dose not exist")
except Exception as e:
    print(e)
else:
    print(f.read())
    f.close()
finally:
    print("run complete")

run complete

In [20]:
f= open('a1.txt')
if f.name =='a1.txt':
    raise Exception

Exception:

In [21]:
# take 2 numbers as user input
# write a program for division of these 2 numbers
# handle ZeroDivisionError and valueError

In [27]:
a = int(input("enter a first no:"))
b = int(input("enter a second no:"))
try:
    result = a/b 
    print(result)
except ZeroDivisionError:
    print("Error: Division by zero is not allowed.")
except ValueError:
    print("Error: Please enter valid numeric values.")

enter a first no: 2
enter a second no: 0

Error: Division by zero is not allowed.

In [28]:
 # array

In [16]:
import numpy as np

In [17]:
a = np.array([2,44.5,True,'array'])

In [18]:
a

array(['2', '44.5', 'True', 'array'], dtype='<U32')

In [103]:
import pandas as pd

In [104]:
roll = pd.Series([1,2,3,45])
name = pd.Series(['sia','ravi','geet','ajeenkya','avinash'])
marks= pd.Series([87,67,98,59,96])

In [105]:
df = pd.DataFrame({
    'id':roll,
    'name':name,
    'marks':marks
})

In [106]:
df

     id      name  marks
0   1.0       sia     87
1   2.0      ravi     67
2   3.0      geet     98
3  45.0  ajeenkya     59
4   NaN   avinash     96

In [107]:
df.ndim

2

In [108]:
df.shape

(5, 3)

In [109]:
df.size

15

In [110]:
df.columns

Index(['id', 'name', 'marks'], dtype='object')

In [111]:
"""
url -> https://mitu.co.in/dataset

downlod all the datasets starting with student*
put them in the sam file folder as ur current working directory
""";

In [112]:
pwd

'C:\\Users\\Samruddhi Deshmukh'

In [113]:
df = pd.read_csv("student.csv")
df;

In [114]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [115]:
df.shape

(10, 5)

In [116]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [117]:
# student1.csv

In [118]:
df = pd.read_csv("student1.csv")

In [119]:
df

    1     anil  TE  56.77  22
0   2     amit  TE  59.77  21
1   3   aniket  BE  76.88  19
2   4  ajinkya  TE  69.66  20
3   5     asha  TE  63.28  20
4   6   ayesha  BE  49.55  20
5   7     amar  BE  65.34  19
6   8    amita  BE  68.33  23
7   9     amol  TE  56.75  20
8  10    anmol  BE  78.66  21

In [120]:
col = ['rol','name','class','marks','age']

In [121]:
df = pd.read_csv('student1.csv', names=col)
df

   rol     name class  marks  age
0    1     anil    TE  56.77   22
1    2     amit    TE  59.77   21
2    3   aniket    BE  76.88   19
3    4  ajinkya    TE  69.66   20
4    5     asha    TE  63.28   20
5    6   ayesha    BE  49.55   20
6    7     amar    BE  65.34   19
7    8    amita    BE  68.33   23
8    9     amol    TE  56.75   20
9   10    anmol    BE  78.66   21

In [122]:
# student3.tsv

In [127]:
df = pd.read_csv('student3.tsv', sep = '\t')

In [128]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21